languageCode = "en-us"
title = "Digital Marketing Director"
baseURL = "https://digitalmarketingdirector.com/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

# [params]
<link rel="apple-touch-icon" sizes="180x180" href="https://raw.githubusercontent.com/foofeh/hugo-theme-massively/master/exampleSite/static/uploads/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="https://raw.githubusercontent.com/foofeh/hugo-theme-massively/master/exampleSite/static/uploads/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="https://raw.githubusercontent.com/foofeh/hugo-theme-massively/master/exampleSite/static/uploads/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false

[languages]
[languages.en]
  languageName = "English"

